// 22 quotes 

const quoteList = [
    "You wouldn't have the desire if you didn't have the ability to achieve it - Emerson.",
    "Practice creates confidence. Confidence empowers you.",
    "Just becuase it's taking time, doesn't mean it's not happening.",
    "It takes courage to examine your life and to decide that there are things you would like to change, and it takes even more courage to do something about it. - Sue Hadfield",
    "If you want to be successful, you will need to be your own cheerleader. You must push yourself becuase no one else is going to do it for you.",
    "What if... everything you are going through is preparing you for what you asked for?",
    "Doing your best in this moment, puts you in the best place for the next monment. - Oprah Winfrey",
    "Every next level of your life will demand a different you. - Leonardo Dicaprio",
    "Life has a way of testing you to see if you are ready for what you asked for. Make sure you are always prepared.",
    "Enjoy every moment of the journey, and appreciate where you are in this moment instead of focusing on how far you have to go. - Mandy Hale", 
    "You are not supposed to be the same person you were a year, month, day, or even five seconds ago. You are designed to grow. - Mel Robbins",
    "Never allow waiting to become a habit. Live your dreams and take risks. Life is happening now. - Paulo Coelho",
    "If you do not ask, the answer will always be no.",
    "Nothing is a coincidence. Everything you're experiencing is meant to happen exactly how it is happening. Embrace the lessons. Be greatful.",
    "Don't be in such a rush to figure everything out. Embrace the unknown and let your life surprise you.",
    "Results happen over time, not overnight. Work hard, stay consistent and be patient.",
    "If everything was perfect, you would never learn and you would never grow. - Beyonce",
    "Stop worrying about what could go wrong and think of what could go right. - Tony Robbins",
    "An ounce of action is worth a ton of theory.",
    "Hold the vision, trust the process.",
    "You are the architect of your own life.",
    "The biggest risk you take is not taking one. - Pitbull"
];

// colours generated by Coolors. 
// const colors = ["#C96480", "#B47978", "#7798AB", "#49392C", "#4B4A67", "#852A49"];

let wrapperDiv = document.getElementById("wrapper");
let quoteText = document.getElementById("quote-text");
let quoteButton = document.getElementById("quote-button");

quoteButton.addEventListener("click", function() {
  const randomIndex = Math.floor(Math.random() * quoteList.length);
  const randomQuote = quoteList[randomIndex];

  quoteText.innerText = randomQuote;
  wrapperDiv.style.backgroundColor = colors[randomIndex];
});

